name: benchmark
services:
  client:
    image: benchmark-client:1.0.0
    build: ./client/
    depends_on:
      server:
        condition: service_healthy
  server:
    image: benchmark-server:1.0.0
    build: ./server/
    healthcheck:
      test: curl http://localhost:8080?number=1 || exit 1
      retries: 5
      interval: 5s
networks:
  default:
    name: benchmark
